version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: serde
    versions:
    - 1.0.122
    - 1.0.123
    - 1.0.124
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: ctrlc
    versions:
    - 3.1.7
    - 3.1.8
  - dependency-name: libloading
    versions:
    - 0.6.7
