# [aura_consensus]
# public_keys should be a list containing all authorities publick keys
validator_set = ["2039b89d46f8a630b68824a6f851e2a5855c1d21915ee4f35fb09d44f1e6e37f",
               "2c8a35450e1d198e3834d933a35962600c33d1d0f8f6481d6e08f140791374d0",
               "a986f7e76ec53d46d78f69fb2d76ae9378b439a6db43afba7a6761a01ccf3a7d",
            ]
# this should be integer defining waiting queue size
block_list_size = 5
# this should be integer defining each round time in seconds.
step_time = 5
# this should be a list of indentity numbers(integers) from 0 to size of public_keys
# this should be order in respective to public_keys.
validator_ids = [0, 1, 2]
# force-sealing will ensure blocks will be produced even if there are no transactions.
force_sealing = true
# start_time will be used to calculate round number
start_time = 3423423
# round_number at the start_time
round_number = 0 
