[package]
name = "p2plib"
version = "0.1.0"
authors = ["Pankajm"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils" }
futures = "0.3.1"
libp2p = "0.14.0-alpha.1"
async-std = "1.4.0"
env_logger = "0.7.1"