[package]
name = "node"
version = "0.1.0"
authors = ["Pankajm"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
consensus = { path = "../consensus" }
utils = { path = "../utils" }
schema = { path = "../schema" }
p2plib = { path = "../p2plib" }
hex = "^0.4"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "^0.10"
chrono = { version = "0.4", features = ["serde"] }
libp2p = "^0.15"
futures = "0.3.1"
async-std = "^1.4"
env_logger = "0.7.1"
lazy_static = "^1.4"
db_service = { path = "../db_service"}
[profile.release]
panic = 'abort'