[package]
name = "node"
version = "0.1.0"
authors = ["Pankajm"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils" }
lazy_static = "1.4.0"
toml = "0.5.5"
tokio = { version = "0.2.6", features = ["full"] }
futures = "0.3.1"
libp2p = "0.14.0-alpha.1"
async-std = "1.4.0"
libc = "0.2.66"