[package]
name = "node"
version = "0.1.0"
authors = ["Pankajm"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils" }
p2plib = { path = "../p2plib" }
futures = "0.3.1"
libp2p = "^0.15"
async-std = "^1.4"
env_logger = "0.7.1"
lazy_static = "^1.4"