name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: protobuf
      run:  |
            curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/$PROTOC_ZIP
            sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
            sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
            rm -f $PROTOC_ZIP
      env:
        PROTOC_ZIP: protoc-3.7.1-linux-x86_64.zip      
    - name: install
      run:  sudo apt-get install -y software-properties-common curl git build-essential libssl-dev libsodium-dev libsnappy-dev librocksdb-dev pkg-config clang-7 lldb-7 lld-7 libprotobuf-dev protobuf-compiler python3-pip python3-setuptools   
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
